"""add is_published column to post

Revision ID: 3cc23ee0a773
Revises: 6fdb41b11695
Create Date: 2023-09-02 17:49:37.996034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cc23ee0a773'
down_revision: Union[str, None] = '6fdb41b11695'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_published', sa.BOOLEAN(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_published')
    # ### end Alembic commands ###
