"""create personal and guest models

Revision ID: cc8e851800ef
Revises: 3cc23ee0a773
Create Date: 2023-09-17 19:49:48.981035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cc8e851800ef'
down_revision: Union[str, None] = '3cc23ee0a773'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personal',
    sa.Column('name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('status', sa.INTEGER(), nullable=False),
    sa.Column('date_publish', sa.TIMESTAMP(), nullable=True),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personal_email'), 'personal', ['email'], unique=True)
    op.create_index(op.f('ix_personal_name'), 'personal', ['name'], unique=False)
    op.create_table('guest',
    sa.Column('name', sa.VARCHAR(length=24), nullable=False),
    sa.Column('email', sa.VARCHAR(length=64), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=16), nullable=True),
    sa.Column('country', sa.VARCHAR(length=24), nullable=True),
    sa.Column('date_publish', sa.TIMESTAMP(), nullable=True),
    sa.Column('personal_id', sa.INTEGER(), nullable=False),
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['personal_id'], ['personal.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_index(op.f('ix_guest_name'), 'guest', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_guest_name'), table_name='guest')
    op.drop_table('guest')
    op.drop_index(op.f('ix_personal_name'), table_name='personal')
    op.drop_index(op.f('ix_personal_email'), table_name='personal')
    op.drop_table('personal')
    # ### end Alembic commands ###
